package com.hkx.momware.data.db

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase


/**
 * DAO implementations associated with that database will be generated by room.
 * This Database class provides instances of the defined DAOs.
 */
@Database(entities = [PlaylistEntity::class], version = 1)
abstract class PlaylistDatabase : RoomDatabase() {

    abstract fun playlistEntityDao(): PlaylistEntityDao

    companion object {
        @Volatile
        private var Instance: PlaylistDatabase? = null

        fun getDatabase(context: Context): PlaylistDatabase {
            return Instance ?: synchronized(this) {
                Room.databaseBuilder(context, PlaylistDatabase::class.java, "playlist_database")
                    /**
                     * Setting this option in your app's database builder means that Room
                     * permanently deletes all data from the tables in your database when it
                     * attempts to perform a migration with no defined migration path.
                     */
                    .fallbackToDestructiveMigration()
                    .build().also { Instance = it }
            }
        }
    }
}
